### ISSUE TITLE
Udacity Site Header quiz does not evaluate properly in some browsers

### ISSUE THREAD

**Issue by sarah-maris** [udacity/fend-issues#59]
Link to quiz: https://classroom.udacity.com/nanodegrees/nd001/parts/d4012321-b4fa-4628-9121-2baf37385560/modules/a605c5ff-eaf7-4882-9c6f-9e65a33c8b59/lessons/7323812069/concepts/75570469630923#

Two students have reported thru Live Help that the font-weight question does not evaluate properly.  I investigated and confirmed that 1) their code is correct and 2) the quiz does fail sometimes.

On my computer the quiz does not work in Chrome Canary:
![does not work canary](https://user-images.githubusercontent.com/6298143/32419429-0887c516-c27a-11e7-9077-a78f8c3c1f06.PNG)

But does work in Chrome with the exact same code:
![works](https://user-images.githubusercontent.com/6298143/32419431-089d659c-c27a-11e7-89a6-c9e2684279b5.PNG)

One interesting difference.  In Chrome the computed font-weight shows up as "normal" but it shows up as "400" in Canary.   I tested using `font-weight: normal` in Canary but that didn't pass either.

More info:  I am working on a Windows machine.  The second student is using Chrome on a mac.  Did not get info about operating system and browser from first student.

**Comment by forbiddenvoid** [comment]
I think that has been fixed. Please resubmit if it pops up again.

**Comment by sarah-maris** [comment]
Not fixed.  Just had another student post the issue in Live Help and
confirmed that it is not working Chrome (does work in Canary)   Will
re-post.
